var  a= 7;
var  b= 9;
// console.log("before swap : a =", a, "b =", b);
var temp = a;
a = b;
b = temp;
// console.log("after swap : a=", a,"b =", b);
var x = 5;
var y = 6;
    x = x+y;
    y = x-y;
    x = x-y;
    // console.log("After swap : x =",x, "y =",y);
    var p = 8;
    var q = 4;
    [p,q] = [q,p];
    console.log("after swap : p =",p, " q =",q);
